# Generated by Django 5.2.8 on 2025-11-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_rename_code_discount_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
