# Generated by Django 5.2.8 on 2025-11-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_inventory_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="variant",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
