# Generated by Django 5.2.8 on 2025-11-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=255)),
                ("success", models.BooleanField()),
                ("http_status_code", models.IntegerField(blank=True, null=True)),
                ("response_time_ms", models.FloatField()),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
