# Generated by Django 5.2.8 on 2025-11-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecheck",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
