# Generated by Django 5.2.8 on 2025-11-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="payment_status",
            new_name="status",
        ),
    ]
