# Generated by Django 5.2.8 on 2025-11-30 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_rename_payment_status_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="order.order",
            ),
        ),
    ]
